Fix loop to not need a missing `true`
Fixes:
```
clone.c:255:14: error: use of undeclared identifier 'true'
    } while (true);
             ^
1 error generated.
```